import React,{useEffect,useState} from 'react';
import{createRoot}from'react-dom/client';
import{createWalletClient,createPublicClient,custom,http,parseEther,formatEther}from'viem';
import artifact from './generated/BakedBeans.json';
import'./style.css';
const OWNER='0x0F8C77d66BE897ded49b2793b71f2A3Eb63CCaA8';
const chain={id:97,name:'BSC Testnet',nativeCurrency:{name:'tBNB',symbol:'tBNB',decimals:18},rpcUrls:{default:{http:['https://bsc-testnet-dataseed.bnbchain.org']}},blockExplorers:{default:{name:'BscScan',url:'https://testnet.bscscan.com'}}};
const pc=createPublicClient({chain,transport:http()});
function App(){const[account,setAccount]=useState();const[contract,setContract]=useState(localStorage.getItem('hiveContract')||'');const[msg,setMsg]=useState('Connect the deployment wallet.');const[amount,setAmount]=useState('0.01');const[stats,setStats]=useState({});
const wallet=()=>createWalletClient({chain,transport:custom(window.ethereum)});
async function ensure(){if(!window.ethereum)throw Error('No injected wallet found. Open this site inside your wallet browser or use a WalletConnect-capable browser.');await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x61'}]}).catch(async()=>window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:'0x61',chainName:'BSC Testnet',nativeCurrency:{name:'tBNB',symbol:'tBNB',decimals:18},rpcUrls:chain.rpcUrls.default.http,blockExplorerUrls:[chain.blockExplorers.default.url]}]}));const[a]=await wallet().requestAddresses();setAccount(a);return a}
async function connect(){try{const a=await ensure();setMsg(a.toLowerCase()===OWNER.toLowerCase()?'Correct deployment wallet connected.':'Wrong wallet. Deployment is locked to the configured owner address.')}catch(e){setMsg(e.shortMessage||e.message)}}
async function deploy(){try{const a=await ensure();if(a.toLowerCase()!==OWNER.toLowerCase())throw Error('Connected wallet does not match configured deployment wallet.');setMsg('Approve the contract deployment in your wallet…');const hash=await wallet().deployContract({account:a,abi:artifact.abi,bytecode:artifact.bytecode});setMsg(`Deployment submitted: ${hash}`);const r=await pc.waitForTransactionReceipt({hash});setContract(r.contractAddress);localStorage.setItem('hiveContract',r.contractAddress);setMsg(`Deployed: ${r.contractAddress}`)}catch(e){setMsg(e.shortMessage||e.message)}}
async function write(fn,args=[],value){try{if(!contract)throw Error('Deploy the contract first.');const a=await ensure();setMsg(`Approve ${fn} in your wallet…`);const hash=await wallet().writeContract({account:a,address:contract,abi:artifact.abi,functionName:fn,args,value});setMsg(`Submitted: ${hash}`);await pc.waitForTransactionReceipt({hash});setMsg(`${fn} confirmed.`);refresh()}catch(e){setMsg(e.shortMessage||e.message)}}
async function refresh(){if(!contract||!account)return;try{const [bal,miners,eggs,rewards,owner]=await Promise.all([pc.readContract({address:contract,abi:artifact.abi,functionName:'getBalance'}),pc.readContract({address:contract,abi:artifact.abi,functionName:'getMyMiners',args:[account]}),pc.readContract({address:contract,abi:artifact.abi,functionName:'getMyEggs',args:[account]}),pc.readContract({address:contract,abi:artifact.abi,functionName:'beanRewards',args:[account]}),pc.readContract({address:contract,abi:artifact.abi,functionName:'owner'})]);setStats({bal:formatEther(bal),miners:String(miners),eggs:String(eggs),rewards:formatEther(rewards),owner})}catch(e){setMsg(e.shortMessage||e.message)}}
useEffect(()=>{refresh()},[contract,account]);
return <main><h1>🐝 BnBeeHive</h1><p className="tag">Build the Hive. Compound the Honey.</p><div className="warn">BSC TESTNET · tBNB ONLY · ORIGINAL BAKEDBEANS LOGIC · NOT AUDITED</div><section><button onClick={connect}>Connect Wallet</button><p>{account||'Not connected'}</p><p className="small">Required deployer: {OWNER}</p></section><section><h2>1. Deploy</h2><button onClick={deploy}>Deploy BakedBeans</button><p className="mono">{contract||'No contract deployed yet'}</p>{contract&&<a href={`${chain.blockExplorers.default.url}/address/${contract}`} target="_blank">View on BscScan</a>}</section><section><h2>2. Seed Market</h2><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal"/><span> tBNB</span><button onClick={()=>write('seedMarket',[],parseEther(amount))}>Seed Market</button><p className="small">Owner-only and one-time. The entered tBNB becomes contract liquidity.</p></section><section><h2>3. BnBeeHive</h2><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal"/><span> tBNB</span><button onClick={()=>write('buyEggs',['0x0000000000000000000000000000000000000000'],parseEther(amount))}>Hire Bees</button><button onClick={()=>write('hatchEggs',['0x0000000000000000000000000000000000000000'])}>Compound Honey</button><button onClick={()=>write('sellEggs')}>Harvest Honey</button><button onClick={refresh}>Refresh</button><div className="grid"><b>Bees</b><span>{stats.miners??'—'}</span><b>Honey (eggs)</b><span>{stats.eggs??'—'}</span><b>Harvest value</b><span>{stats.rewards??'—'} tBNB</span><b>Hive balance</b><span>{stats.bal??'—'} tBNB</span><b>Owner</b><span className="mono">{stats.owner??'—'}</span></div></section><section className="status"><b>Status</b><p>{msg}</p></section><footer>This contract does not generate external yield. Withdrawals depend on BNB/tBNB held by the contract. Testnet tokens have no monetary value.</footer></main>}
createRoot(document.getElementById('root')).render(<App/>);
